package web

/**************************************************************
* 使用到的工具：
* $ go get github.com/jteeuwen/go-bindata/...
$ $ go get github.com/elazarl/go-bindata-assetfs/...
* 嵌入资源的生成方法，在当前目录下运行：
* $ go-bindata-assetfs views/...
***************************************************************/
